version: '2'
services:
  yngx001: 
    image: yuyilun-nginx:0.0.1
    links: 
      - ytomcat001:t01 
      - ytomcat002:t02
    ports: 
      - "80:80" 
    restart: always 
  ytomcat001: 
    image: yuyilun-tomcat8:0.0.1
    ports: 
      - "8081:8080"
    environment:
      TOMCAT_SERVER_ID: tomcat_server_001
    restart: always
  ytomcat002: 
    image: yuyilun-tomcat8:0.0.1
    ports: 
      - "8082:8080"
    environment:
      TOMCAT_SERVER_ID: tomcat_server_002
    restart: always